Added calculation of launch angles of the RF trajectory from the source vertex.
ara-software/AraSim pull request #127
Opened 2024-07-06 16:34 UTC by jflaherty13

Implemented calculation and storage of launch angles of the RF signal from the source vertex to work in conjunction with [AraRoot Pull #68](https://github.com/ara-software/AraRoot/pull/68).  This stores the MCTruth values of the theta and phi launch angles in the Report pointer alongside the MCTruth values of the receiving angles of the signal.  The calculation of the launch angles follows the same framework as the receiving angles, which is a simple conversion of the Cartesian vector into theta and phi.

2024-07-08 14:51 UTC, clark2668 requested changes
Just a couple questions and requests for more clarifying docs.

2024-07-08 14:51 UTC, clark2668 commented on Report.cc
> +    receiveing antenna's coordinate system.
Does it make sense to calculate the _launch_ angle in the frame of the _target_? Wouldn't it make more sense to calculate the launch angle in the frame of the emitter? Or maybe that's what you actually do and the docs are just not quite right?

2024-07-08 14:51 UTC, clark2668 commented on Report.cc
> +
Some documentation about units and convention would be good -- it looks like this is reported in degrees? And with what convention, 0 = up, 180 = down, etc.

2024-07-08 15:21 UTC, jflaherty13 commented on Report.cc
> +
Updated the description to have units and conventions for 0 and 180.

2024-07-08 15:23 UTC, jflaherty13 commented on Report.cc
> +    receiveing antenna's coordinate system.
Maybe my description was vague.  This calculates the launch angle theta and phi in station-centric coordinates, while launch angle in the Ray Tracer is calculated relative to the target vector.  I've updated the description of the function to hopefully make this more clear.

2024-07-09 13:57 UTC, jflaherty13 commented
> Just a couple questions and requests for more clarifying docs.

Hey Brian.  Are my new pushes the changes you're looking for?  If so, could you approve them?  I can't merge until you've approved the changes.

2024-07-09 14:25 UTC, clark2668 approved these changes

2024-07-09 14:25 UTC, clark2668 commented
Whoops, sorry, looks okay to me.

2024-07-09 15:55 UTC, merged